In [ ]:
# IMPORT COOL LIBRARIES
import pandas as pd
import numpy  as np
import os

In [ ]:
# SET PATHS OF 3 COOL CSVs

FILENAME_sales_phases_funnel_df = os.path.join(os.getcwd(), r'data/sale_phases_funnel.csv')
FILENAME_zipcode_df = os.path.join(os.getcwd(), r'data/zipcode_eae.csv')
FILENAME_meteo_df = os.path.join(os.getcwd(), r'data/meteo_eae.csv')

In [ ]:
FILENAME_sales_phases_funnel_df 
FILENAME_zipcode_df
FILENAME_meteo_df

'/Users/juanmontesinos/Documents/eae/DMBI/final/final_assignment_dmbi/data/meteo_eae.csv'

In [ ]:

#CREATING COOL DATAFRAMES WITH THE DATA TYPES SET FROM START

def dataFrameCreate():


    # SET PATHS OF 3 COOL CSVs
    FILENAME_sales_phases_funnel_df = os.path.join(os.getcwd(), r'data/sale_phases_funnel.csv')
    FILENAME_zipcode_df = os.path.join(os.getcwd(), r'data/zipcode_eae.csv')
    FILENAME_meteo_df = os.path.join(os.getcwd(), r'data/meteo_eae.csv')


    #SALES FUNNEL DATAFRAME

    #Dictionary with data types
    SALES_TYPES = {'LEAD_ID':'str','FINANCING_TYPE':'str',
                    'CURRENT_PHASE':'str','PHASE_PRE_KO':'str',
                    'IS_MODIFIED':'bool','ZIPCODE':'str', 
                    'VISITING_COMPANY': 'str', 'KO_REASON': 'str', 
                    'INSTALLATION_PEAK_POWER_KW': 'float64', 
                    'INSTALLATION_PRICE': 'float', 
                    'N_PANELS': 'int', 'CUSOMER_TYPE': 'str' }

    # Reading CSV to create dataframe with datatypes implemented from dictionary and additional date time datatypes.
    sales_phases_funnel_df = pd.read_csv(
        FILENAME_sales_phases_funnel_df, 
        delimiter=';', 
        dtype=SALES_TYPES,
        parse_dates=['OFFER_SENT_DATE', 'CONTRACT_1_DISPATCH_DATE', 
                    'CONTRACT_2_DISPATCH_DATE', 
                    'CONTRACT_1_SIGNATURE_DATE', 
                    'CONTRACT_2_SIGNATURE_DATE',
                    'VISIT_DATE',
                    'TECHNICAL_REVIEW_DATE',
                    'PROJECT_VALIDATION_DATE',
                    'SALE_DISMISSAL_DATE',
                    'KO_DATE'],
                    
        dayfirst=True  # This replaces the dayfirst=True in your to_datetime call
    )



    #ZIPCODE DATAFRAME

    #Dictionary with data types
    ZIPCODE_TYPES = {'ZIPCODE':'str','ZC_LATITUDE':'float64',
                    'ZC_LONGITUDE':'float64','AUTONOMOUS_COMMUNITY':'str',
                    'AUTONOMOUS_COMMUNITY_NK':'str','PROVINCE':'str'}


    # Reading CSV to create dataframe with datatypes implemented from dictionary
    zipcode_df = pd.read_csv(FILENAME_zipcode_df, delimiter=',', dtype=ZIPCODE_TYPES)






    #METEO DATAFRAME

    #Dictionary with data types
    METEO_TYPES = {'temperature': 'float', 'relative_humidity': 'float', 
                'precipitation_rate': 'float', 'wind_speed': 'float', 
                'zipcode': 'str' 
    }

    # Reading CSV to create dataframe with datatypes implemented from dictionary and 
    # additional date time datatype formatted to match the ones from the sales dataframe.
    meteo_df = pd.read_csv(FILENAME_meteo_df, delimiter=';',
        dtype=METEO_TYPES, parse_dates=['date'],  # Replace with actual column name
        date_format='%Y/%m/%d %H:%M:%S.%f'  # This matches your input format
    )

meteo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4114206 entries, 0 to 4114205
Data columns (total 6 columns):
 #   Column              Dtype
---  ------              -----
 0   date                datetime64[ns]
 1   temperature         float64
 2   relative_humidity   float64
 3   precipitation_rate  float64
 4   wind_speed          float64
 5   zipcode             object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 188.3+ MB

In [41]:
#DROPPING DUPLICATES FOR ALL DATAFRAMES

#creating the drop duplicate function
def dropDupli():
    print('There are ', sales_phases_funnel_df.duplicated().sum(), ' duplicate rows in sales_funnel_df before duplicate cleaning') 
    print('There are ', zipcode_df.duplicated().sum(), ' duplicate rows in zipcode_df before duplicate cleaning')
    print('There are ', meteo_df.duplicated().sum(), ' duplicate rows in meteo_df before duplicate cleaning') 
    sales_phases_funnel_df.drop_duplicates(inplace=True)
    zipcode_df.drop_duplicates(inplace=True)
    meteo_df.drop_duplicates(inplace=True)
    print('There are ', sales_phases_funnel_df.duplicated().sum(), ' duplicate rows in sales_funnel_df after duplicate cleaning') 
    print('There are ', zipcode_df.duplicated().sum(), ' duplicate rows in zipcode_df after duplicate cleaning')
    print('There are ', meteo_df.duplicated().sum(), ' duplicate rows in meteo_df after duplicate cleaning')

dropDupli()

There are  0  duplicate rows in sales_funnel_df before duplicate cleaning
There are  0  duplicate rows in zipcode_df before duplicate cleaning
There are  0  duplicate rows in meteo_df before duplicate cleaning
There are  0  duplicate rows in sales_funnel_df after duplicate cleaning
There are  0  duplicate rows in zipcode_df after duplicate cleaning
There are  0  duplicate rows in meteo_df after duplicate cleaning

In [ ]:
# CLEANING SALES FUNNEL DATAFRAME - 1


# DELETE UNUSABLE LEADS FUNCTION

# Drop rows where KO_REASON is "Unreachable"
def delete_unreachable_leads():
    global sales_phases_funnel_df
    sales_phases_funnel_df = sales_phases_funnel_df[~((sales_phases_funnel_df['CURRENT_PHASE'] == 'KO') & (sales_phases_funnel_df['KO_REASON'] == 'Unreachable'))]
    # Reset the index of the updated DataFrame
    sales_phases_funnel_df.reset_index(drop=True, inplace=True)

# Verify the changes
#print(sales_phases_funnel_df.isnull().sum())
#print(sales_phases_funnel_df.head())

delete_unreachable_leads()

sales_phases_funnel_df

,LEAD_ID,FINANCING_TYPE,CURRENT_PHASE,PHASE_PRE_KO,IS_MODIFIED,OFFER_SENT_DATE,CONTRACT_1_DISPATCH_DATE,CONTRACT_2_DISPATCH_DATE,CONTRACT_1_SIGNATURE_DATE,CONTRACT_2_SIGNATURE_DATE,...,PROJECT_VALIDATION_DATE,SALE_DISMISSAL_DATE,KO_DATE,ZIPCODE,VISITING_COMPANY,KO_REASON,INSTALLATION_PEAK_POWER_KW,INSTALLATION_PRICE,N_PANELS,CUSOMER_TYPE
0,C8877823,cash,Validated project,Validated project,False,2024-01-01,2024-01-03,NaT,2024-01-09,NaT,...,2024-02-22,NaT,NaT,8629,Internal,NaN,4.800,9562.77,12,Individual household
1,C2068654,cash,KO,Initial Offer,False,2024-01-01,NaT,NaT,NaT,NaT,...,NaT,NaT,2024-01-02,29730,Internal,Useless Contact,1.600,4650.92,4,Individual household
2,C1925058,cash,KO,Commercial visit,False,2024-01-01,NaT,NaT,NaT,NaT,...,NaT,NaT,2024-01-03,23007,Internal,Product. Vertical Building / Condominiums,3.600,7438.55,9,Community of owners
3,C3357155,cash,KO,Initial Offer,False,2024-01-01,NaT,NaT,NaT,NaT,...,NaT,NaT,2024-01-04,17007,Internal,Useless Contact,3.200,6580.33,8,SME
4,C5104785,cash,KO,Initial Offer,False,2024-01-01,NaT,NaT,NaT,NaT,...,NaT,NaT,2024-01-04,46210,Internal,Useless Contact,2.800,5937.57,7,Individual household
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28859,C2986619,cash,KO,Winback,False,2024-12-30,NaT,NaT,NaT,NaT,...,NaT,NaT,2025-03-20,43895,Internal,Useless Contact. Not Interested,1.515,5944.00,3,Individual household
28860,C1071478,cash,KO,Initial Offer,False,2024-12-30,NaT,NaT,NaT,NaT,...,NaT,NaT,2025-01-08,7400,Internal,Useless Contact. Not Interested,3.535,8522.83,7,SME
28861,C8350262,financed,Validated project,Validated project,False,2024-12-30,2025-01-08,2025-01-10,2025-01-08,2025-01-10,...,2025-01-22,NaT,NaT,47430,Internal,NaN,6.060,11457.01,12,Individual household
28862,C5247567,cash,KO,Initial Offer,False,2024-12-30,NaT,NaT,NaT,NaT,...,NaT,NaT,2025-01-02,18370,Internal,Useless Contact. Not Interested,2.020,6743.50,4,SME
28863,C4570179,cash,KO,Initial Offer,False,2024-12-30,NaT,NaT,NaT,NaT,...,NaT,NaT,2025-01-01,35018,Internal,Useless Contact. Incorrect Phone Number,5.555,10520.33,11,Individual household

In [ ]:
# CLEANING SALES FUNNEL DATAFRAME - 2

# REMOVE OUTLIERS FUNCTION


def delete_outliers():
    global sales_phases_funnel_df
    # Calculate Q1 (25th percentile) and Q3 (75th percentile)
    Q1 = sales_phases_funnel_df['INSTALLATION_PRICE'].quantile(0.25)
    Q3 = sales_phases_funnel_df['INSTALLATION_PRICE'].quantile(0.75)

    # Calculate the Interquartile Range (IQR)
    IQR = Q3 - Q1

    # Identify outliers inside a new Data Frame
    outliers_df = sales_phases_funnel_df[(sales_phases_funnel_df['INSTALLATION_PRICE'] < (Q1 - 1.5 * IQR)) | 
                                     (sales_phases_funnel_df['INSTALLATION_PRICE'] > (Q3 + 1.5 * IQR))]

    # Print the number of outliers
    print(f"Number of outliers: {len(outliers_df)}")

    # Update sales_phases_funnel_df to exclude the outliers
    sales_phases_funnel_df = sales_phases_funnel_df[~((sales_phases_funnel_df['INSTALLATION_PRICE'] < (Q1 - 1.5 * IQR)) | 
                                                  (sales_phases_funnel_df['INSTALLATION_PRICE'] > (Q3 + 1.5 * IQR)))]

    # Print the DataFrame without outliers
    print("DataFrame without outliers:")
    print(sales_phases_funnel_df)

    # Print the DataFrame with only outliers
    print("DataFrame with only outliers:")
    print(outliers_df)


#sales_phases_funnel_df
#outliers_df

In [ ]:
#-----------FOR THE BOIS----------------------

#--------LIBRARIES FOR THE BOIS (THE ONES I USED, THE USUAL ONES)-----------

#COOL LIBRARIES
import pandas as pd
import numpy as np
import os
from tools.logs import log_wrap
import logging



# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

# Create logger instance
logger = logging.getLogger(__name__)




# SET PATHS OF 3 COOL CSVs
FILENAME_sales_phases_funnel_df = os.path.join(os.getcwd(), r'data/sale_phases_funnel.csv')
FILENAME_zipcode_df = os.path.join(os.getcwd(), r'data/zipcode_eae.csv')
FILENAME_meteo_df = os.path.join(os.getcwd(), r'data/meteo_eae.csv')


#SETTING TYPES
#Sales
SALES_TYPES = {'LEAD_ID':'str','FINANCING_TYPE':'str',
                    'CURRENT_PHASE':'str','PHASE_PRE_KO':'str',
                    'IS_MODIFIED':'bool','ZIPCODE':'str', 
                    'VISITING_COMPANY': 'str', 'KO_REASON': 'str', 
                    'INSTALLATION_PEAK_POWER_KW': 'float64', 
                    'INSTALLATION_PRICE': 'float', 
                    'N_PANELS': 'int', 'CUSOMER_TYPE': 'str' }

#Zipcosdes
ZIPCODE_TYPES = {'ZIPCODE':'str','ZC_LATITUDE':'float64',
                    'ZC_LONGITUDE':'float64','AUTONOMOUS_COMMUNITY':'str',
                    'AUTONOMOUS_COMMUNITY_NK':'str','PROVINCE':'str'}

#Meteo
METEO_TYPES = {'temperature': 'float', 'relative_humidity': 'float', 
            'precipitation_rate': 'float', 'wind_speed': 'float', 
            'zipcode': 'str' 
}





#----------FUNCTIONS FOR THE BOIS-----------

#CREATE 3 COOL DATAFRAMES FUNCTION
#Creates 3 super cool dataframes from the CSVs with the data types set from the start.
def dataFrameCreate():

    #SALES FUNNEL DATAFRAME

    #Dictionary with data types
   

    #Reading CSV to create dataframe with datatypes implemented from dictionary and additional date time datatypes.
    sales_phases_funnel_df = pd.read_csv(
        FILENAME_sales_phases_funnel_df, 
        delimiter=';', 
        dtype=SALES_TYPES,
        parse_dates=['OFFER_SENT_DATE', 'CONTRACT_1_DISPATCH_DATE', 
                    'CONTRACT_2_DISPATCH_DATE', 
                    'CONTRACT_1_SIGNATURE_DATE', 
                    'CONTRACT_2_SIGNATURE_DATE',
                    'VISIT_DATE',
                    'TECHNICAL_REVIEW_DATE',
                    'PROJECT_VALIDATION_DATE',
                    'SALE_DISMISSAL_DATE',
                    'KO_DATE'],
                    
        dayfirst=True  # This replaces the dayfirst=True in your to_datetime call
    )

    logger.info('sales_phases_funnel_df created')



    #ZIPCODE DATAFRAME

    # Reading CSV to create dataframe with datatypes implemented from dictionary
    zipcode_df = pd.read_csv(FILENAME_zipcode_df, delimiter=',', dtype=ZIPCODE_TYPES)


    logger.info('zipcodedf created')




    #METEO DATAFRAME

    # Reading CSV to create dataframe with datatypes implemented from dictionary and 
    # additional date time datatype formatted to match the ones from the sales dataframe.
    meteo_df = pd.read_csv(FILENAME_meteo_df, delimiter=';',
        dtype=METEO_TYPES, parse_dates=['date'],  # Replace with actual column name
        date_format='%Y/%m/%d %H:%M:%S.%f'  # This matches your input format
    )

    logger.info('meteo_df created')
    list_of_dfs = [sales_phases_funnel_df, zipcode_df, meteo_df]

    return list_of_dfs
    



list_of_dfs = dataFrameCreate()




#--GLOBAL CLEANING FUNCTION--


#DROPPING DUPLICATES FOR ALL DATAFRAMES

#creating the drop duplicate function
def dropDupli(dfs):
    #log
    logger.info(f'There are {dfs[0].duplicated().sum()} duplicate rows in sales_funnel_df before duplicate cleaning') 
    logger.info(f'There are {dfs[1].duplicated().sum()} duplicate rows in zipcode_df before duplicate cleaning')
    logger.info(f'There are {dfs[2].duplicated().sum()} duplicate rows in meteo_df before duplicate cleaning')  
    #DroppingDupli
    dfs[0].drop_duplicates(inplace=True)
    dfs[1].drop_duplicates(inplace=True)
    dfs[2].drop_duplicates(inplace=True)
    # Log after
    logger.info(f'There are {dfs[0].duplicated().sum()} duplicate rows in sales_funnel_df after duplicate cleaning') 
    logger.info(f'There are {dfs[1].duplicated().sum()} duplicate rows in zipcode_df after duplicate cleaning')
    logger.info(f'There are {dfs[2].duplicated().sum()} duplicate rows in meteo_df after duplicate cleaning')

    return dfs  # Return dfs instead of undefined variables



list_of_dfs = dropDupli(list_of_dfs)



# --SALES FUNNEL DATAFRAME CLEANING FUCTIONS--


#DELETE UNUSABLE LEADS FUNCTION 

# Drop rows where KO_REASON is "Unreachable"
def delete_unreachable_leads(dfs):
    dfs[0] = dfs[0][~((dfs[0]['CURRENT_PHASE'] == 'KO') & (dfs[0]['KO_REASON'] == 'Unreachable'))]
    # Reset the index of the updated DataFrame
    dfs[0].reset_index(drop=True, inplace=True)
    logger.info('Unreachable leads deleted')
    return dfs

list_of_dfs = delete_unreachable_leads(list_of_dfs)




# REMOVE OUTLIERS FUNCTION


def delete_outliers(dfs):
    # Calculate Q1 (25th percentile) and Q3 (75th percentile)
    Q1 = dfs[0]['INSTALLATION_PRICE'].quantile(0.25)
    Q3 = dfs[0]['INSTALLATION_PRICE'].quantile(0.75)
    

    # Calculate the Interquartile Range (IQR)
    IQR = Q3 - Q1

    # Identify outliers inside a new Data Frame
    outliers_df = dfs[0][(dfs[0]['INSTALLATION_PRICE'] < (Q1 - 1.5 * IQR)) | 
                                     (dfs[0]['INSTALLATION_PRICE'] > (Q3 + 1.5 * IQR))]

    # Print the number of outliers
    logger.info('outliers_df dataframe created')
    logger.info(f'Number of outliers: {len(outliers_df)}')
    
    # Update sales_phases_funnel_df to exclude the outliers
    sales_phases_funnel_df = dfs[0][~((dfs[0]['INSTALLATION_PRICE'] < (Q1 - 1.5 * IQR)) | 
                                                  (dfs[0]['INSTALLATION_PRICE'] > (Q3 + 1.5 * IQR)))]
    logger.info('outliers removed from sales_phases_funnel_df')
    dfs.append(outliers_df)
    logger.info(f'outliers_df dataframe added to list_of_dfs')
    return dfs
    


list_of_dfs = delete_outliers(list_of_dfs)


#This is how you would use it in th final etl:
'''
from tools.cleaning import dataFrameCreate, dropDupli, delete_unreachable_leads, delete_outliers



list_of_dfs = dataFrameCreate()
list_of_dfs = dropDupli(list_of_dfs)
list_of_dfs = delete_unreachable_leads(list_of_dfs) #this one we may exclude
list_of_dfs = delete_outliers(list_of_dfs)

print(list_of_dfs)
'''

2025-03-08 01:28:18,222 - __main__ - INFO - sales_phases_funnel_df created
2025-03-08 01:28:18,230 - __main__ - INFO - zipcodedf created
2025-03-08 01:28:21,663 - __main__ - INFO - meteo_df created
2025-03-08 01:28:21,740 - __main__ - INFO - There are 0 duplicate rows in sales_funnel_df before duplicate cleaning
2025-03-08 01:28:21,742 - __main__ - INFO - There are 0 duplicate rows in zipcode_df before duplicate cleaning
2025-03-08 01:28:22,397 - __main__ - INFO - There are 0 duplicate rows in meteo_df before duplicate cleaning
2025-03-08 01:28:23,117 - __main__ - INFO - There are 0 duplicate rows in sales_funnel_df after duplicate cleaning
2025-03-08 01:28:23,118 - __main__ - INFO - There are 0 duplicate rows in zipcode_df after duplicate cleaning
2025-03-08 01:28:23,747 - __main__ - INFO - There are 0 duplicate rows in meteo_df after duplicate cleaning
2025-03-08 01:28:23,753 - __main__ - INFO - Unreachable leads deleted
2025-03-08 01:28:23,754 - __main__ - INFO - outliers_df dataframe created
2025-03-08 01:28:23,754 - __main__ - INFO - Number of outliers: 1096
2025-03-08 01:28:23,756 - __main__ - INFO - outliers removed from sales_phases_funnel_df
2025-03-08 01:28:23,757 - __main__ - INFO - outliers_df dataframe added to list_of_dfs

''